stages:
  - build
  - test
  - deploy

before_script:
  - npm install
  - echo "Installing dependencies...brrrrrr"

build-job:
  stage: build
  script:
    - echo "Building the application...brrrrrr"
#     - CI=true npm run build --no-progress --silent

test-job:
  stage: test
  script:
    - echo "Testing the application...brrrrrr"

deploy-job:
  stage: deploy
  script:
    - echo "Deploying the application...brrrrrr"
